global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using UnoKeyboardAcceleratorDemo.DataContracts;
global using UnoKeyboardAcceleratorDemo.DataContracts.Serialization;
global using UnoKeyboardAcceleratorDemo.Models;
global using UnoKeyboardAcceleratorDemo.Presentation;
global using UnoKeyboardAcceleratorDemo.Services.Caching;
global using UnoKeyboardAcceleratorDemo.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
